version: "3.9"
services:
  pyAPI:
    build: ./py
    command: uvicorn src.server.app:app --reload --workers 1 --host 0.0.0.0 --port 5050
    volumes:
      - ./py:/pyserver
    ports:
      - "5050:5050"
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
#    links:
#      - redis
#    redis:
#      image: redis
#  db:
#    image: mongodb
#    ports:
#      - "8001:27017"